# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f2e29048ef535a07f6f9060e7ceb11a4de48ef9e649c93a4871f665d5aa27e87585c4775169e1c5e041ac88788ffe47bd36830bcc166588de6598852f2cfbec

test:
  secret_key_base: 792b9d6db5b8b9b4af721dbaabc78067862a3900fce8eee99c50fb66f6e32469ce2a574e2c73379cd7641862a7f4f31f9595b1b60c5d08baa1c009e3daf51c3e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
